---
# Role tasks

- name: Configure secure tty terminals
  template:
    src: securetty.j2
    dest: /etc/securetty
    owner: root
    group: root
    mode: 0600
    backup: yes
  vars:
    securetty_to_manage: >-
      {{ securetty_terminals
         + ((securetty_load_from_hostvars)
            | ternary(securetty_hostvars | default([]) | flatten, [])) }}
  tags:
    - role::securetty
